// source: dolt/services/eventsapi/v1alpha1/client_event.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var dolt_services_eventsapi_v1alpha1_event_constants_pb = require('../../../../dolt/services/eventsapi/v1alpha1/event_constants_pb.js');
goog.object.extend(proto, dolt_services_eventsapi_v1alpha1_event_constants_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.dolt.services.eventsapi.v1alpha1.ClientEvent', null, global);
goog.exportSymbol('proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute', null, global);
goog.exportSymbol('proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric', null, global);
goog.exportSymbol('proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.MetricOneofCase', null, global);
goog.exportSymbol('proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest', null, global);
goog.exportSymbol('proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.displayName = 'proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.oneofGroups_);
};
goog.inherits(proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.displayName = 'proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dolt.services.eventsapi.v1alpha1.ClientEvent.repeatedFields_, null);
};
goog.inherits(proto.dolt.services.eventsapi.v1alpha1.ClientEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolt.services.eventsapi.v1alpha1.ClientEvent.displayName = 'proto.dolt.services.eventsapi.v1alpha1.ClientEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.repeatedFields_, null);
};
goog.inherits(proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.displayName = 'proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.displayName = 'proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.prototype.toObject = function(opt_includeInstance) {
  return proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, 0),
value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute;
  return proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.dolt.services.eventsapi.v1alpha1.AttributeID} */ (reader.readEnum());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional AttributeID id = 1;
 * @return {!proto.dolt.services.eventsapi.v1alpha1.AttributeID}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.prototype.getId = function() {
  return /** @type {!proto.dolt.services.eventsapi.v1alpha1.AttributeID} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.AttributeID} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.prototype.setId = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.MetricOneofCase = {
  METRIC_ONEOF_NOT_SET: 0,
  DURATION: 1,
  COUNT: 2
};

/**
 * @return {proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.MetricOneofCase}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.getMetricOneofCase = function() {
  return /** @type {proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.MetricOneofCase} */(jspb.Message.computeOneofCase(this, proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.toObject = function(opt_includeInstance) {
  return proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.toObject = function(includeInstance, msg) {
  var f, obj = {
duration: (f = msg.getDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
count: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
metricId: jspb.Message.getFieldWithDefault(msg, 100, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric;
  return proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDuration(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    case 100:
      var value = /** @type {!proto.dolt.services.eventsapi.v1alpha1.MetricID} */ (reader.readEnum());
      msg.setMetricId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDuration();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMetricId();
  if (f !== 0.0) {
    writer.writeEnum(
      100,
      f
    );
  }
};


/**
 * optional google.protobuf.Duration duration = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.getDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} returns this
*/
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.setDuration = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.clearDuration = function() {
  return this.setDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.hasDuration = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 count = 2;
 * @return {number}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.setCount = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.clearCount = function() {
  return jspb.Message.setOneofField(this, 2, proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.hasCount = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional MetricID metric_id = 100;
 * @return {!proto.dolt.services.eventsapi.v1alpha1.MetricID}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.getMetricId = function() {
  return /** @type {!proto.dolt.services.eventsapi.v1alpha1.MetricID} */ (jspb.Message.getFieldWithDefault(this, 100, 0));
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.MetricID} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.prototype.setMetricId = function(value) {
  return jspb.Message.setProto3EnumField(this, 100, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.dolt.services.eventsapi.v1alpha1.ClientEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
endTime: (f = msg.getEndTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
type: jspb.Message.getFieldWithDefault(msg, 4, 0),
attributesList: jspb.Message.toObjectList(msg.getAttributesList(),
    proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.toObject, includeInstance),
metricsList: jspb.Message.toObjectList(msg.getMetricsList(),
    proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolt.services.eventsapi.v1alpha1.ClientEvent;
  return proto.dolt.services.eventsapi.v1alpha1.ClientEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    case 4:
      var value = /** @type {!proto.dolt.services.eventsapi.v1alpha1.ClientEventType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = new proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute;
      reader.readMessage(value,proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.deserializeBinaryFromReader);
      msg.addAttributes(value);
      break;
    case 6:
      var value = new proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric;
      reader.readMessage(value,proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.deserializeBinaryFromReader);
      msg.addMetrics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolt.services.eventsapi.v1alpha1.ClientEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getAttributesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute.serializeBinaryToWriter
    );
  }
  f = message.getMetricsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp start_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
*/
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.setStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.clearStartTime = function() {
  return this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp end_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
*/
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.setEndTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.clearEndTime = function() {
  return this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ClientEventType type = 4;
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventType}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.getType = function() {
  return /** @type {!proto.dolt.services.eventsapi.v1alpha1.ClientEventType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventType} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * repeated ClientEventAttribute attributes = 5;
 * @return {!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute>}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.getAttributesList = function() {
  return /** @type{!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute, 5));
};


/**
 * @param {!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute>} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
*/
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.setAttributesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.addAttributes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.dolt.services.eventsapi.v1alpha1.ClientEventAttribute, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.clearAttributesList = function() {
  return this.setAttributesList([]);
};


/**
 * repeated ClientEventMetric metrics = 6;
 * @return {!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric>}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.getMetricsList = function() {
  return /** @type{!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric, 6));
};


/**
 * @param {!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric>} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
*/
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.setMetricsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric}
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.addMetrics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.dolt.services.eventsapi.v1alpha1.ClientEventMetric, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.ClientEvent.prototype.clearMetricsList = function() {
  return this.setMetricsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
machineId: jspb.Message.getFieldWithDefault(msg, 1, ""),
extra: jspb.Message.getFieldWithDefault(msg, 2, ""),
version: jspb.Message.getFieldWithDefault(msg, 3, ""),
platform: jspb.Message.getFieldWithDefault(msg, 4, 0),
eventsList: jspb.Message.toObjectList(msg.getEventsList(),
    proto.dolt.services.eventsapi.v1alpha1.ClientEvent.toObject, includeInstance),
app: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest;
  return proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMachineId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtra(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {!proto.dolt.services.eventsapi.v1alpha1.Platform} */ (reader.readEnum());
      msg.setPlatform(value);
      break;
    case 5:
      var value = new proto.dolt.services.eventsapi.v1alpha1.ClientEvent;
      reader.readMessage(value,proto.dolt.services.eventsapi.v1alpha1.ClientEvent.deserializeBinaryFromReader);
      msg.addEvents(value);
      break;
    case 6:
      var value = /** @type {!proto.dolt.services.eventsapi.v1alpha1.AppID} */ (reader.readEnum());
      msg.setApp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMachineId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExtra();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPlatform();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.dolt.services.eventsapi.v1alpha1.ClientEvent.serializeBinaryToWriter
    );
  }
  f = message.getApp();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional string machine_id = 1;
 * @return {string}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.getMachineId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.setMachineId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string extra = 2;
 * @return {string}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.getExtra = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.setExtra = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string version = 3;
 * @return {string}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Platform platform = 4;
 * @return {!proto.dolt.services.eventsapi.v1alpha1.Platform}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.getPlatform = function() {
  return /** @type {!proto.dolt.services.eventsapi.v1alpha1.Platform} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.Platform} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * repeated ClientEvent events = 5;
 * @return {!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEvent>}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.getEventsList = function() {
  return /** @type{!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEvent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dolt.services.eventsapi.v1alpha1.ClientEvent, 5));
};


/**
 * @param {!Array<!proto.dolt.services.eventsapi.v1alpha1.ClientEvent>} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} returns this
*/
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.setEventsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dolt.services.eventsapi.v1alpha1.ClientEvent}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.addEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.dolt.services.eventsapi.v1alpha1.ClientEvent, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.clearEventsList = function() {
  return this.setEventsList([]);
};


/**
 * optional AppID app = 6;
 * @return {!proto.dolt.services.eventsapi.v1alpha1.AppID}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.getApp = function() {
  return /** @type {!proto.dolt.services.eventsapi.v1alpha1.AppID} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.dolt.services.eventsapi.v1alpha1.AppID} value
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest} returns this
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsRequest.prototype.setApp = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse;
  return proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolt.services.eventsapi.v1alpha1.LogEventsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.dolt.services.eventsapi.v1alpha1);
